### ISSUE TITLE
feat : 중간 거리 근처의 역 정보 필터링

### ISSUE THREAD

**Issue by sduu** [sduu/where-center#13]
## 작업 개요
중간 거리 근처의 역 정보를 필터링해서 보여주는 기능 구현

## Todo

-   [ ] ✏ 좌표가 범위안에 포함되어있는지 체크 후 마커 표시
-   [ ] ✏ 역 정보 리스트 요소 생성
-   [ ] ✏ 역 정보 리스트 요소 클릭 시 정보 모달 노출
